### ISSUE TITLE
/usr/local/bin/DisplaySpaces not there? 

### ISSUE THREAD

**Issue by joefromct** [apierz/chunkbar.widget#4]
Hi,

I don't have `/usr/local/bin/DisplaySpaces` at that location... new install on mojave.

Is there something in brew I need to pick up?  

This is referenced here:
https://github.com/apierz/chunkbar.widget/blob/3e83e5f96118544eb9d01ac80af9030ec6a4c59a/scripts/screens#L4

Thanks,

**Comment by apierz** [comment]
The script that is referring to is this one:
https://github.com/kinglouie/DisplaySpaces

which I used when chunkc was having output problems. I think the problems are now fixed so I can probably get rid of it and switch back to just using chunkc to get the display data. I'll probably update it when I have a chance to test it out. Thank for finding this, I should have switched it out a while ago.

**Comment by apierz** [comment]
The new screens script is saved in this branch for now: https://github.com/apierz/chunkbar.widget/blob/screens-reconfig/scripts/screens

It should work but I'll wait until I can test it to merge it in with the master branch. See code below if you want to try it out instead of using DisplaySpaces:


```
#!/bin/bash

chunkc=/usr/local/bin/chunkc

active=$($chunkc tiling::query -d id)
total=$($chunkc tiling::query -D 1 | tail -c 1)
current=$($chunkc tiling::query --window name)
mode=$($chunkc tiling::query -d mode)

echo "$mode@$active@$total@$(sh ../chunkbar.widget/scripts/activeWindow.sh)"
```

**Comment by apierz** [comment]
Ok, tested and merged into master. Their should be no need for DisplaySpaces now. Thanks again for the spot, I forgot that I kludged it like this.
